sudo: required
dist: trusty
language: c++
before_install:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get -qq update; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get install -y libtokyocabinet-dev libkyototycoon-dev kyototycoon libkyotocabinet-dev libhiredis-dev; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update; brew upgrade; brew install xz tokyo-cabinet kyoto-cabinet kyoto-tycoon; fi
script:
  - make && PATH=$PATH:`pwd`/bin make test
os:
  - linux
  - osx
env:
  - CGL_DEBUG=1
  - CGL_DEBUG=ultra
matrix:
  exclude:
    # The default OSX env doesn't have a version that supports
    # -fsanitize=address.
    - env: CGL_DEBUG=ultra
      os: osx
